server:
  # 端口
  port: 8082
spring:
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.qq.com
    # 协议
    protocol: smtps
    # 编码格式
    default-encoding: utf-8
    # 授权码（在邮箱开通服务时获取）
    password: xfzsiturvecbbeii
    # 发送者邮箱地址
    username: 1004102689@qq.com
    # 端口（不同邮箱端口号不同）
    port: 465

  # rabbitmq配置
  rabbitmq:
    # 用户名
    username: admin
    # 密码
    password: admin
    # 服务器地址
    host: 101.200.221.9
    # 端口
    port: 5672
    listener:
      simple:
        #开启手动确认
        acknowledge-mode: manual

